import './globals.css';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

// PROVIDERS
import { AppProviders } from '../providers/app.provider';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'NewMusic Challenge Frontend',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
    ...pageProps
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <AppProviders pageProps={pageProps}>{children}</AppProviders>
            </body>
        </html>
    );
}
